### ISSUE TITLE
Change runes definition to css classes

### ISSUE THREAD

**Issue by afk-mcz** [Rotonde/rotonde-client#43]
Currently the runes are added by java script to the feed and portal, if it was changed to a css classes system, it would be easier to customize.

For example: 

```html
<t class="portal">
	<a href="dat://"><i class="rune-self"></i>afk_mcz</a>
</t>
<t class="portal">
	<a href="dat://"><i class="rune-both"></i>user_who_follows_you</a>
</t>
<t class="portal">
	<a href="dat://"><i class="rune-follow"></i>user_who_doesn't</a>
</t>
```
```css
:root {
	--rune-self: "▲";
	--rune-both: "@";
	--rune-follow: "~";
}

.rune-self {
	content: var(--rune-self);
}

.rune-both {
	content: var(--rune-both);

}

.rune-follow {
	content: var(--rune-follow);
}

:custom-css {
	--rune-self: "▲";
	--rune-both: "◢";
	--rune-follow: "◣";
}

```
